# Generated by Django 3.2.5 on 2021-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Логин')),
                ('firstname', models.CharField(max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('date_creation', models.PositiveIntegerField(verbose_name='Дата создания записи')),
                ('birthday_year', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
        ),
    ]
