# Generated by Django 3.2.5 on 2021-07-17 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_creation',
            field=models.PositiveIntegerField(default=datetime.datetime(2021, 7, 17, 23, 35, 16, 588803), verbose_name='Дата создания записи'),
        ),
    ]
