# Generated by Django 3.2.5 on 2021-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания записи'),
        ),
    ]
